### ISSUE TITLE
error on this plugin

### ISSUE THREAD

**Issue by rubenteste** [zesage/panorama#16]
hi just download the project from github 
and when i try to run it just give me this error: 
didn't change enything on the code:

The following assertion was thrown during paint():
'package:flutter/src/rendering/layer.dart': Failed assertion: line 1586 pos 12: 'value!.storage.every((double component) => component.isFinite)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Panorama file:///home/ruben/Transfer%C3%AAncias/panorama-master/example/lib/main.dart:66:11
When the exception was thrown, this was the stack: 
#2      TransformLayer.transform= (package:flutter/src/rendering/layer.dart:1586:12)
#3      PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:576:13)
#4      RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2298:25)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
...
The following RenderObject was being processed when the exception was fired: RenderTransform#65483
...  needs compositing
...  parentData: top=NaN; left=NaN; width=90.0; height=75.0; offset=Offset(NaN, NaN) (can use size)
...  constraints: BoxConstraints(w=90.0, h=75.0)
...  layer: TransformLayer#f9c72 DETACHED
...    engine layer: TransformEngineLayer#fa266
...    offset: Offset(0.0, 0.0)
...    transform: [0] 0.5,0.0,0.9,532.2
[1] 0.2,1.0,-0.1,-206.9
[2] -0.9,0.3,0.5,686.0
[3] 0.0,0.0,0.0,1.0
...  size: Size(90.0, 75.0)
...  transform matrix: [0] NaN,NaN,NaN,NaN
[1] NaN,NaN,NaN,NaN
[2] NaN,NaN,NaN,NaN
[3] NaN,NaN,NaN,NaN
...  origin: Offset(45.0, 37.5)
...  alignment: null
...  textDirection: ltr
...  transformHitTests: true
RenderObject: RenderTransform#65483
  needs compositing
  parentData: top=NaN; left=NaN; width=90.0; height=75.0; offset=Offset(NaN, NaN) (can use size)
  constraints: BoxConstraints(w=90.0, h=75.0)
  layer: TransformLayer#f9c72 DETACHED
    engine layer: TransformEngineLayer#fa266
    offset: Offset(0.0, 0.0)
    transform: [0] 0.5,0.0,0.9,532.2
[1] 0.2,1.0,-0.1,-206.9
[2] -0.9,0.3,0.5,686.0
[3] 0.0,0.0,0.0,1.0
  size: Size(90.0, 75.0)
  transform matrix: [0] NaN,NaN,NaN,NaN
[1] NaN,NaN,NaN,NaN
[2] NaN,NaN,NaN,NaN
[3] NaN,NaN,NaN,NaN
  origin: Offset(45.0, 37.5)
  alignment: null
  textDirection: ltr
  transformHitTests: true
...  child: RenderOffstage#3bdd5
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=90.0, h=75.0)
...    size: Size(90.0, 75.0)
...    offstage: false
...    child: RenderFlex#7cbde
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=90.0, h=75.0)
...      size: Size(90.0, 75.0)
...      direction: vertical
...      mainAxisAlignment: center
...      mainAxisSize: max
...      crossAxisAlignment: center
...      verticalDirection: down
...      child 1: RenderSemanticsAnnotations#ac26a relayoutBoundary=up1
...        needs compositing
...        parentData: offset=Offset(1.0, 1.5); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=90.0, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(88.0, 48.0)
...        child: _RenderInputPadding#af226 relayoutBoundary=up2
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=90.0, 0.0<=h<=Infinity)
...          size: Size(88.0, 48.0)
...      child 2: RenderDecoratedBox#8e262 relayoutBoundary=up1
...        parentData: offset=Offset(0.0, 49.5); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=90.0, 0.0<=h<=Infinity)
...        size: Size(90.0, 24.0)
...        decoration: BoxDecoration
...          color: Color(0x61000000)
...          borderRadius: BorderRadius.circular(4.0)
...        configuration: ImageConfiguration(bundle: PlatformAssetBundle#9bf52(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...        child: RenderPadding#0a2d0 relayoutBoundary=up2
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=90.0, 0.0<=h<=Infinity)
...          size: Size(90.0, 24.0)
...          padding: EdgeInsets.all(4.0)
...          textDirection: ltr

**Comment by zesage** [comment]
4e9df517ff91071f7ce02f8c76fd2eb8bdf5251d Fixed "component.isFinite" exception, please download the last update and try again.

**Comment by rubenteste** [comment]
in the file panorama.dart is normal the android studio give this error? 
error: The named parameter 'vsync' isn't defined. (undefined_named_parameter at [panorama] lib/panorama.dart:395)


![Captura de ecrã de 2021-01-08 09-50-07](https://user-images.githubusercontent.com/75133022/104001025-f9091b80-5196-11eb-8422-e92611238650.png)

**Comment by rubenteste** [comment]
hey,
i was testing the new update, don't have the initial erros, but if I run the app on the emulator android from android sutdio and i start using the virtual sensors 
the app give this error:

The following assertion was thrown during paint():
'package:flutter/src/rendering/layer.dart': Failed assertion: line 1586 pos 12: 'value!.storage.every((double component) => component.isFinite)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Panorama file:///home/ruben/Transfer%C3%AAncias/panorama-master/example/lib/main.dart:72:16
When the exception was thrown, this was the stack: 
#2      TransformLayer.transform= (package:flutter/src/rendering/layer.dart:1586:12)
#3      PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:576:13)
#4      RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2298:25)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
...
The following RenderObject was being processed when the exception was fired: RenderTransform#0d43a
...  needs compositing
...  parentData: top=NaN; left=NaN; width=100.0; height=75.0; offset=Offset(NaN, NaN) (can use size)
...  constraints: BoxConstraints(w=100.0, h=75.0)
...  layer: TransformLayer#86a44 DETACHED
...    engine layer: TransformEngineLayer#85a0c
...    offset: Offset(0.0, 0.0)
...    transform: [0] 0.0,-0.0,1.0,8732.7
[1] -0.0,1.0,0.0,0.1
[2] -1.0,-0.0,0.0,9153.3
[3] 0.0,0.0,0.0,1.0
...  size: Size(100.0, 75.0)
...  transform matrix: [0] NaN,NaN,NaN,NaN
[1] NaN,NaN,NaN,NaN
[2] NaN,NaN,NaN,NaN
[3] NaN,NaN,NaN,NaN
...  origin: Offset(50.0, 37.5)
...  alignment: null
...  textDirection: ltr
...  transformHitTests: true
RenderObject: RenderTransform#0d43a
  needs compositing
  parentData: top=NaN; left=NaN; width=100.0; height=75.0; offset=Offset(NaN, NaN) (can use size)
  constraints: BoxConstraints(w=100.0, h=75.0)
  layer: TransformLayer#86a44 DETACHED
    engine layer: TransformEngineLayer#85a0c
    offset: Offset(0.0, 0.0)
    transform: [0] 0.0,-0.0,1.0,8732.7
[1] -0.0,1.0,0.0,0.1
[2] -1.0,-0.0,0.0,9153.3
[3] 0.0,0.0,0.0,1.0
  size: Size(100.0, 75.0)
  transform matrix: [0] NaN,NaN,NaN,NaN
[1] NaN,NaN,NaN,NaN
[2] NaN,NaN,NaN,NaN
[3] NaN,NaN,NaN,NaN
  origin: Offset(50.0, 37.5)
  alignment: null
  textDirection: ltr
  transformHitTests: true
...  child: RenderOffstage#ca07b
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=100.0, h=75.0)
...    size: Size(100.0, 75.0)
...    offstage: false
...    child: RenderFlex#682ed
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=100.0, h=75.0)
...      size: Size(100.0, 75.0)
...      direction: vertical
...      mainAxisAlignment: center
...      mainAxisSize: max
...      crossAxisAlignment: center
...      verticalDirection: down
...      child 1: RenderSemanticsAnnotations#253df relayoutBoundary=up1
...        needs compositing
...        parentData: offset=Offset(6.0, 1.5); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=100.0, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(88.0, 48.0)
...        child: _RenderInputPadding#8209a relayoutBoundary=up2
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=100.0, 0.0<=h<=Infinity)
...          size: Size(88.0, 48.0)
...      child 2: RenderDecoratedBox#a31e6 relayoutBoundary=up1
...        parentData: offset=Offset(0.0, 49.5); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=100.0, 0.0<=h<=Infinity)
...        size: Size(100.0, 24.0)
...        decoration: BoxDecoration
...          color: Color(0x61000000)
...          borderRadius: BorderRadius.circular(4.0)
...        configuration: ImageConfiguration(bundle: PlatformAssetBundle#6eefc(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...        child: RenderPadding#68a14 relayoutBoundary=up2
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=100.0, 0.0<=h<=Infinity)
...          size: Size(100.0, 24.0)
...          padding: EdgeInsets.all(4.0)
...          textDirection: ltr

**Comment by zesage** [comment]
try the last update f9a668755c701ac8f6dd4941055d147dedc33797

**Comment by rubenteste** [comment]
is working,  thank you bro

**Comment by zesage** [comment]
c95857ef72d622a392c06824fc86f125684e3c5c fixed called on null in _updateTexture

**Comment by rlazom** [comment]
With the c95857e commit the issue "The getter 'mesh' was called on null" is fixed.

**Comment by rubenteste** [comment]
ty guys

**Comment by xuanvan229** [comment]
Hi @zesage , Look like the error still appear

flutter: hello Instance of 'ViewProps'
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during paint():
flutter: 'package:flutter/src/rendering/layer.dart': Failed assertion: line 1584 pos 12:
flutter: 'value!.storage.every((double component) => component.isFinite)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   Transform
flutter:   file:///Users/hongxuan/Data/flutter/.pub-cache/hosted/pub.dartlang.org/panorama-0.3.2/lib/panorama.dart:370:18
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TransformLayer.transform= (package:flutter/src/rendering/layer.dart:1584:12)
flutter: #3      PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:576:13)
flutter: #4      RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2296:25)
flutter: #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #7      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2616:15)
flutter: #8      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
flutter: #9      RenderStack.paint (package:flutter/src/rendering/stack.dart:621:7)
flutter: #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #12     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2616:15)
flutter: #13     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
flutter: #14     RenderStack.paint (package:flutter/src/rendering/stack.dart:621:7)
flutter: #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
flutter: #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
flutter: #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #23     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2616:15)
flutter: #24     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
flutter: #25     RenderStack.paint (package:flutter/src/rendering/stack.dart:621:7)
flutter: #26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #28     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2616:15)
flutter: #29     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:407:5)
flutter: #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #32     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
flutter: #33     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:551:11)
flutter: #34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #36     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
flutter: #37     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
flutter: #38     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1860:15)
flutter: #39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #41     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
flutter: #42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #44     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
flutter: #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #46     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
flutter: #47     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
flutter: #48     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
flutter: #49     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:456:19)
flutter: #50     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:895:13)
flutter: #51     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
flutter: #52     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #53     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
flutter: #54     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
flutter: #58     _invoke (dart:ui/hooks.dart:157:10)
flutter: #59     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
flutter: #60     _drawFrame (dart:ui/hooks.dart:120:31)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderTransform#00349:
flutter:   needs compositing
flutter:   creator: Transform ← Positioned ← Stack ← StreamBuilder<Null> ← Stack ← Listener ← _GestureSemantics
flutter:     ← RawGestureDetector ← GestureDetector ← Panorama ← Positioned ← Stack ← ⋯
flutter:   parentData: top=NaN; left=NaN; width=120.0; height=90.0; offset=Offset(NaN, NaN) (can use size)
flutter:   constraints: BoxConstraints(w=120.0, h=90.0)
flutter:   layer: TransformLayer#71c8b DETACHED
flutter:   size: Size(120.0, 90.0)
flutter:   transform matrix:
flutter:     [0] NaN,NaN,NaN,NaN
flutter:     [1] NaN,NaN,NaN,NaN
flutter:     [2] NaN,NaN,NaN,NaN
flutter:     [3] NaN,NaN,NaN,NaN
flutter:   origin: Offset(60.0, 45.0)
flutter:   alignment: null
flutter:   textDirection: ltr
flutter:   transformHitTests: true
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child: RenderOffstage#f3e4b NEEDS-PAINT
flutter:       child: RenderFlex#ebb3d NEEDS-PAINT
flutter:         child 1: RenderSemanticsAnnotations#72c36 relayoutBoundary=up1 NEEDS-PAINT
flutter:           child: _RenderInputPadding#b4b9d relayoutBoundary=up2 NEEDS-PAINT
flutter:             child: RenderConstrainedBox#71139 relayoutBoundary=up3 NEEDS-PAINT
flutter:         child 2: RenderDecoratedBox#6ecc6 relayoutBoundary=up1 NEEDS-PAINT
flutter:           child: RenderPadding#3b3cb relayoutBoundary=up2 NEEDS-PAINT
flutter:             child: RenderPositionedBox#af5e1 relayoutBoundary=up3 NEEDS-PAINT
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: SemanticsNode#100(Rect.fromLTRB(0.0, 0.0, 0.0, 0.0), invisible) (with null) tried to set a non-finite rect.
flutter: Another exception was thrown: 'package:flutter/src/rendering/layer.dart': Failed assertion: line 1584 pos 12: 'value!.storage.every((double component) => component.isFinite)': is not true.
flutter: Another exception was thrown: SemanticsNode#100(Rect.fromLTRB(0.0, 0.0, 0.0, 0.0), invisible) (with null) tried to set a non-finite rect.
